server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elyoj?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
#  # Redis 配置
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#      timeout: 10s
  
  # JSON 序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 自定义配置
ely:
  security:
    # JWT 配置
    jwt:
      # 使用更强的密钥 (至少256位/32字节)
      secret: T2p3MUswZ25la1daNkFPSnFGS0FYRUM1RHRBSWxpQlg0N0dFODBOcHo5Yg==
      expiration: 86400000 # 24小时过期
      header: Authorization
      token-prefix: Bearer 